Extract re-usable publish workflow
pulumi/ci-mgmt pull request #1007
Opened 2024-06-26 14:06 UTC by danielrbradley

Remove the large amount of duplication by moving the release-related jobs into a re-usable workflow and calling from the existing `release.yml` and `prerelease.yml` workflows.

Stacked on top of:
- https://github.com/pulumi/ci-mgmt/pull/1006

Here's a diff between `prerelease.yml` and `release.yml`. The observed changes are:
1. Extra `IS_PRERELEASE: true` env var
2. Optional extra `create_docs_build` job in `release.yml`.
3. Customised goreleaser args
4. `enableMacosRunner` is disabled for pre-release.
5. Workflow name and tags filters.

```diff
4d3
<   IS_PRERELEASE: true
22a22,40
>   #{{ if .Config.publishRegistry -}}#
>   create_docs_build:
>     name: create_docs_build
>     needs: publish_go_sdk
>     runs-on: #{{ .Config.runner.default }}#
>     steps:
>       - name: Dispatch Metadata build
>         uses: peter-evans/repository-dispatch@v3
>         with:
>           token: ${{ secrets.PULUMI_BOT_TOKEN }}
>           repository: pulumi/registry
>           event-type: resource-provider
>           client-payload: |-
>             {
>               "project": "${{ github.repository }}",
>               "project-shortname": "#{{ .Config.provider }}#",
>               "ref": "${{ github.ref_name }}"
>             }
>   #{{ end -}}#
79,80c97
<         args: -p #{{ .Config.parallel }}# -f .goreleaser.prerelease.yml --rm-dist --skip-validate --timeout
<           #{{ .Config.timeout }}#m0s
---
>         args: -p #{{ .Config.parallel }}# release --rm-dist --timeout #{{ .Config.timeout }}#m0s
143a161,181
> 
>   clean_up_release_labels:
>     name: Clean up release labels
>     #{{ if .Config.publishRegistry -}}#
>     needs: create_docs_build
>     #{{ else }}#
>     needs: tag_sdk
>     #{{- end }}#
>     runs-on: #{{ .Config.runner.default }}#
>     steps:
>     - name: Checkout Repo
>       uses: actions/checkout@v4
>     - name: Clean up release labels
>       uses: pulumi/action-release-by-pr-label@main
>       with:
>         command: "clean-up-release-labels"
>         repo: ${{ github.repository }}
>         commit: ${{ github.sha }}
>       env:
>         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> 
273,274c311
<       # Prelease is run often but we only have 5 concurrent macos runners, so we only test after the stable release.
<       enableMacosRunner: false
---
>       enableMacosRunner: true
276c313
< name: prerelease
---
> name: release
280c317,318
<     - v*.*.*-**
---
>     - v*.*.*
>     - "!v*.*.*-**"
```

2024-06-27 05:57 UTC, thomas11 commented on provider-ci/internal/pkg/templates/bridged-provider.config.yaml
>  actionVersions:
where did those go, and why is the top-level property+comment still there?

2024-06-27 07:55 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider.config.yaml
>  actionVersions:
Sorry, this diff is a little confusing having merged the PRs it was stacked on top of. These are changes from https://github.com/pulumi/ci-mgmt/pull/1003 - these values were only used in the setup-tools action so they're just used directly in there to remove a layer of indirection.

I need to rebase and update this PR today following all the other PRs tomorrow.

2024-06-27 20:13 UTC, danielrbradley commented
Bah - failed the last test run because I mis-typed the pre-release tag 🤦 

Re-running now with the extra simplification in too: https://github.com/pulumi/pulumi-xyz/actions/runs/9702992517

2024-06-27 22:39 UTC, guineveresaenger requested changes

2024-06-27 22:39 UTC, guineveresaenger commented on provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
> +    if: inputs.isPrerelease == false
We only kick off a docs build for tagged releases; not for default branch builds.
Since we [set `isPrerelease` to `false` on the `main` Workflow](https://github.com/pulumi/ci-mgmt/pull/1007/files#diff-eca440a839435c66c59ad89b1d9cd3ca3013db7a8389523f61c45647c60509d7R89) I'm not sure that this condition is enough. Is there something I'm missing?

It's probably going to result in a harmless no-op on the registry but we probably don't want to do that regardless.

2024-06-28 08:48 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/.github/workflows/publish.yml
> +    if: inputs.isPrerelease == false
Oops that was a typo - releases from `main` should definitely be pre-releases. Have pushed a fix.

Have also added more validation to ensure we don't try to release stable releases with '-' or '+' in the version (e.g. `-alpha` or `+dev).

2024-06-28 14:49 UTC, danielrbradley commented
Follow-up test of default branch build: https://github.com/pulumi/pulumi-xyz/actions/runs/9714690944

2024-06-28 18:22 UTC, merged