Fix publish-go-sdk globbing
pulumi/ci-mgmt pull request #1051
Opened 2024-08-06 22:21 UTC by blampe

The current globbing for publish-go-sdk breaks publishing for docker-build because
* `go.*` doesn't match anything (probably a typo of `*.go`)
* `go/**` also doesn't match anything because the SDK module is located under `sdk/go/dockerbuild` instead of `sdk`.

The result is an [almost-empty](https://github.com/pulumi/pulumi-docker-build/tree/sdk/go/dockerbuild/v0.0.4/sdk/go/dockerbuild) SDK branch.

This PR changes the globbing to match any `.go` files under the SDK path.

2024-08-07 07:50 UTC, iwahbe reviewed
I think the `go.*` is for `go.mod` and `go.sum`. I'm not sure why the `go/**` doesn't capture `go/dockerbuild`. I would lean towards moving docker to publish in the same place as all other providers, but I'm less familiar with native provider publishing.

2024-08-07 08:11 UTC, danielrbradley requested changes
This oddity is occurring because docker-build is a special case that puts its `go.mod` in a different location to every other provider.

The globs are calculated relative to the `source` argument. For all other providers the source is `sdk`, but for docker-build it's `sdk/go/dockerbuild`.

The quick fix is to add a conditional special-case for docker-build, so if it's a different source directory, we'll just assume we want everything in that folder.

The better fix here would be to align docker-build with the other providers so we can make our ci-scripts more uniform with less special options, but that would now be a breaking change for the Go SDK, so I don't think this is possible in the short term.

2024-08-07 08:11 UTC, danielrbradley commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
```suggestion
      files: sdkModuleDir == "sdk" ? `\
go.*
go/**
!*.tar.gz` : "**",
```

2024-08-07 17:31 UTC, blampe commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
@danielrbradley what about something like this?
```
**/go.mod
**/go.sum
**/*.go
```

2024-08-07 19:20 UTC, danielrbradley commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
That doesn't work because it will pick up all othe other folders in `sdk` such as `sdk/nodejs` which still contain stub `go.mod` files from when they were published in-place.

2024-08-07 19:48 UTC, blampe commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
@danielrbradley do you have an example? I'm wondering if that's actually a problem - I would assume they aren't even usable.

2024-08-07 19:48 UTC, danielrbradley commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
https://github.com/pulumi/pulumi-azure/blob/master/sdk/nodejs/go.mod

2024-08-07 19:50 UTC, danielrbradley commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
It wouldn't break anything per se, but it would include additional files that we don't need or want published.

2024-08-07 20:11 UTC, blampe commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
> it would include additional files that we don't need or want published.

But that's orthogonal isn't it? Presumably we want to stop generating these fake modules?

On the flip side, it's not unreasonable to imagine publishing a separate module for and SDK with generics or something. In other words we shouldn't assume anything about where or how many modules there might be. It's our goof for generating fake modules, but we've been publishing them for ages and this action isn't the right place to take care of them.

2024-08-08 12:19 UTC, danielrbradley commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
Yes, we might want to remove these files at some point, but I think they still have some effect for local testing scenarios.

> On the flip side, it's not unreasonable to imagine publishing an additional module for an SDK with generics or something

There's lots of hypotheticals, but this tooling is only being used by us internally right now, so we should focus on the only two setups we're using right now–publishing the root `sdk` module, or publishing a more specific sub-folder. For the latter, it seems reasonable that we just include all files. We only even need to specify this argument for most providers right now because of the oddities of how the go module accidentally includes all the other SDKs.

I would suggest just adding the conditional as I proposed.

2024-08-08 17:09 UTC, blampe commented on native-provider-ci/src/steps.ts
>  !*.tar.gz`,
Sure, I made the change and left a pointer to https://github.com/pulumi/pulumi/issues/5403.

2024-08-08 18:23 UTC, danielrbradley approved these changes

2024-08-08 21:20 UTC, merged