Don't fail the upgrade check job if we can't open a PR
pulumi/ci-mgmt pull request #1129
Opened 2024-11-05 15:50 UTC by danielrbradley

Docs for continue-on-error:
> Prevents a job from failing when a step fails. Set to true to allow a job to pass when this step fails.

Failing the job results in a P1 issue being opened. We've already opened an issue to track the pending upgrade, so we'll just exit cleanly if the PR can't be made.

2024-11-05 16:08 UTC, VenelinMartinov requested changes
Can we please clarify what the workflow for people who consume this is? We use failed jobs to see which provider upgrades have failed.

2024-11-05 16:32 UTC, danielrbradley commented
> Can we please clarify what the workflow for people who consume this is? We use failed jobs to see which provider upgrades have failed.

Could you expand on what you're wanting changed here?

2024-11-05 16:54 UTC, guineveresaenger commented on provider-ci/test-providers/cloudflare/.github/workflows/upgrade-provider.yml
This file should not be here, we might need to revisit empty templates?

2024-11-05 17:19 UTC, iwahbe approved these changes
The change makes sense to me. I think you need to clarify (in the comments, please) how this should be used in the wild.

2024-11-05 17:46 UTC, VenelinMartinov commented
Yeah, currently the workflow for provider upgrades is:

For each open provider upgrade issue:
1. Check if it has a corresponding PR.
2. If it does, try to merge it.
3. If it doesn't, see if we had a failure in the upgrade workflow.
4. If the job failed run the upgrade manually.

I am concerned that feedback we used to have of the workflow failing is now lost and we'd have to dig in github logs to identify the failed upgrades.

I'd love for us not to make this already manual and laborious process even harder by hiding the fact that the workflow has failed. This has to be applied across 60 bridged providers, all of which have slightly different behaviours and annoyances and it has to happen every week.


Can we consider something here to make sure the process doesn't get worse? Perhaps the workflow can comment on the original PR about a failure with a link to the failed workflow?

2024-11-05 21:09 UTC, VenelinMartinov approved these changes
Thanks for fixing 🚀

2024-11-05 21:12 UTC, guineveresaenger approved these changes

2024-11-05 22:08 UTC, merged

2024-11-06 08:48 UTC, iwahbe commented
> Yeah, currently the workflow for provider upgrades is:
> 
> For each open provider upgrade issue:
> 
> 1. Check if it has a corresponding PR.
> 2. If it does, try to merge it.
> 3. If it doesn't, see if we had a failure in the upgrade workflow.
> 4. If the job failed run the upgrade manually.
> 
> I am concerned that the feedback we used to have of the workflow failing is now lost and we'd have to dig in github logs to identify the failed upgrades.
> 
> I'd love for us not to make this already manual and laborious process even harder by hiding the fact that the workflow has failed. This has to be applied across 60 bridged providers, all of which have slightly different behaviours and annoyances and it has to happen every week.
> 
> Can we consider something here to make sure the process doesn't get worse? Perhaps the workflow can comment on the original PR about a failure with a link to the failed workflow? If not, can we at least clarify what the expected workflow is now, and make sure everyone is aware of it?

@VenelinMartinov Just to clarify, this change is maintaining the "current process". After this change, we will still get a P1 if `upgrade-provider` fails to stand up an issue. Due to this change, we won't get a P1 if `upgrade-provider` succeeds in standing up an issue but fails in raising an associated PR (since we were already alerted by the issue). We didn't have feedback that the workflow failed before 5 days ago (when we merged https://github.com/pulumi/ci-mgmt/pull/1110). The workflow for provider upgrades remains unchanged. This PR gets us back to the same place as we were 6 days ago.