Change how Gorelease strips internal changelog messages
pulumi/ci-mgmt pull request #150
Opened 2022-03-07 15:46 UTC by stack72

2022-03-07 18:27 UTC, guineveresaenger requested changes
I think this is going to improve things but I have a concern that it's going to catch real commit messages accidentally.

2022-03-07 18:27 UTC, guineveresaenger commented on provider-ci/lib/goreleaser.js
> +                    "internal",
should we keep the square brackets as part of the pattern though? we don't want to accidentally exclude any commits that just have this word in them?

2022-03-07 18:27 UTC, guineveresaenger commented on provider-ci/providers/aiven/repo/.goreleaser.yml
> +    - internal
I think we should come up with a way to escape the square brackets so they're part of the regex.

2022-03-07 18:27 UTC, guineveresaenger commented on provider-ci/providers/aiven/repo/.goreleaser.yml
> +    - internal
I think we should come up with a way to generate this to say `[internal]`.

2022-03-07 21:52 UTC, guineveresaenger commented on provider-ci/providers/aiven/repo/.goreleaser.yml
> +    - WinternalW
This doesn't look right either.. we want it to still say `\Wchore\W` no?

2022-03-07 21:58 UTC, stack72 commented on provider-ci/providers/aiven/repo/.goreleaser.yml
> +    - WinternalW
The \ isn’t being kept in the generate… that’s weird

2022-03-08 14:52 UTC, jkodroff approved these changes

2022-03-08 17:08 UTC, guineveresaenger approved these changes
LGTM! Thanks!

2022-03-08 17:09 UTC, merged