Add option to switch schema tool
pulumi/ci-mgmt pull request #274
Opened 2022-10-27 21:15 UTC by viveklak

2022-10-28 01:45 UTC, lblackstone approved these changes

2022-10-28 18:32 UTC, guineveresaenger requested changes
Unfortunately, it appears there's differences in incantation between the two schema tools.

I want to say that adding an option to choose isn't strictly necessary here either - I think a plain cutover is reasonably safe - but either way we should discuss more.

2022-10-28 18:32 UTC, guineveresaenger commented on provider-ci/src/steps.ts
> +      ? "schema-tools compare ${{ env.PROVIDER }} master --local-path=provider/cmd/pulumi-resource-${{ env.PROVIDER }}/schema.json >> $GITHUB_ENV\n"
For pulumi/schema-tools, we need to be [explicit with the `-o` flag here](https://github.com/pulumi/schema-tools/blob/master/cmd/compare.go#L29) - I notice pulumi/schema-tools defaults to `master` and that is not the default branch for every provider (pulumi-artifactory being an example but there are others).
Something like `-o github.event.repository.default_branch` should work for all cases. 

Additionally, in Mikhail's schema tools, there is no default nor an `-o` flag, but we still should not hard code master here.

2022-10-28 18:32 UTC, guineveresaenger commented on provider-ci/src/config.ts
> +    preferredSchemaChecker: z.string().default("mikhailshilkov/schema-tools"),
I'm curious why we're making this configurable.
Also wondering why we're defaulting to Mikhail's tool.

2022-10-28 18:35 UTC, viveklak commented on provider-ci/src/config.ts
> +    preferredSchemaChecker: z.string().default("mikhailshilkov/schema-tools"),
Because this is the current default. My hope is we roll this out in a few providers as we upgrade them and validate things work as expected. Once the tier 1 providers are updated we can switch the default.

2022-10-28 18:46 UTC, thomas11 commented on provider-ci/providers/auth0/repo/.github/workflows/main.yml
> +        repo: pulumi/schema-tools
You made the schema-tools version configurable, but there are also several places such as this one where the switch is hard-coded. What's the reasoning behind that?

2022-10-28 19:21 UTC, viveklak reviewed
As discussed in-person, the plan here is to instead add `pulumi/schema-tools` comment in addition to existing `schema-tools` for non-tier1 providers. Once we feel confident the coverage is accurate we can cut over to `pulumi/schema-tools`

2022-10-28 19:56 UTC, viveklak commented on provider-ci/providers/auth0/repo/.github/workflows/main.yml
> +        repo: pulumi/schema-tools
This (and all files in the auth0/repo directory) are generated by the tool - in this case the pulumi one was explicitly opted-in here: https://github.com/pulumi/ci-mgmt/pull/274/files#diff-a4be1b53045f8817dbfd12f8cd71c655048b06d0cc2ef084bf4717b677e05a77R2.

2022-10-28 19:57 UTC, viveklak commented on provider-ci/providers/auth0/repo/.github/workflows/main.yml
> +        repo: pulumi/schema-tools
As mentioned in https://github.com/pulumi/ci-mgmt/pull/274#pullrequestreview-1160555851 I plan on instead adding a parallel evaluation for pulumi/schema-tools on some non-tier1 providers. Once we have a little bit of confidence, we will switch entirely to the pulumi version and make that the preferred tool.

2022-10-31 11:12 UTC, danielrbradley approved these changes
I think the approach of not yet changing the default is good - do a gradual rollout and check there's not unintended impact. Only changes I'd suggest is avoiding string types - be more specific on allowed values, though given this might only be short-lived it might not matter much.

2022-10-31 11:12 UTC, danielrbradley commented on provider-ci/src/config.ts
> +    preferredSchemaChecker: z.string().default("mikhailshilkov/schema-tools"),
I'd suggest using an explicit union to restrict the valid input types. I.e. something like:

```typescript
preferredSchemaChecker: z.enum(["mikhailshilkov/schema-tools", "pulumi/schema-tools"]).default("mikhailshilkov/schema-tools")
```

2022-10-31 11:12 UTC, danielrbradley commented on provider-ci/src/steps.ts
> +export function InstallSchemaChecker(preferredSchemaChecker: string): Step {
It might be nice to make the valid set of inputs explicit here:

```suggestion
type PreferredSchemaChecker = "mikhailshilkov/schema-tools" | "pulumi/schema-tools"
export function InstallSchemaChecker(preferredSchemaChecker: PreferredSchemaChecker): Step {
```

This will mean that the compiler will tell you if we update the allowed config values but forget to handle the addtional cases here.

2023-03-06 09:21 UTC, iwahbe commented
Is this PR still worth carrying forward? It looks like we are still relying on @mikhailshilkov's repo:

https://github.com/pulumi/ci-mgmt/blob/bb2bd5cb4dbf7ce3a8fbc2285ab3695280e7e61b/provider-ci/providers/auth0/repo/.github/workflows/main.yml#L154-L158

CC @thomas11 @guineveresaenger @lblackstone @danielrbradley

2023-03-06 10:14 UTC, danielrbradley commented
@iwahbe we should definitely get off Mikhail's repo and onto our own. We've already switched to this version for azure-native and it's fine so maybe could just roll this out in one go now. Looks like a bunch of conflicts too so might be worth just opening a new PR.

2023-05-03 01:07 UTC, iwahbe commented
I opened https://github.com/pulumi/ci-mgmt/issues/404 to track.

2023-05-03 01:36 UTC, iwahbe commented
Closing in favor of https://github.com/pulumi/ci-mgmt/pull/405.

2023-05-03 01:36 UTC, closed without merging