fix: Fix conditional check to see if pulumi binary is in PATH
pulumi/ci-mgmt pull request #333
Opened 2023-02-09 00:54 UTC by rquitales

Previous conditional check always returns true, even if the the pulumi binary does not exist. This commit fixes this logical check.

Ran `make` in the `provider-ci` folder after updating `src`.

2023-02-09 03:34 UTC, AaronFriel requested changes
The PR looks good, but contains unrelated changes.

2023-02-09 03:34 UTC, AaronFriel commented on provider-ci/src/make.ts
> +  );
Nit: pull requests are harder to review when they contain unrelated coding style changes.

2023-02-09 03:34 UTC, AaronFriel commented on provider-ci/src/make-bridged-provider.ts
> +    };
I'd like this commit reduced to the semantic changes.

2023-02-09 17:54 UTC, rquitales commented
> The PR looks good, but contains unrelated changes.

That's probably due to running `make` (ie all targets). Have removed formatting changes in the last patchset.

2023-02-09 17:56 UTC, iwahbe approved these changes
New semantics looks good. I don't see how it affects `make.ts`, so it would be great if that change went away.

2023-02-09 23:44 UTC, AaronFriel approved these changes

2023-02-09 23:44 UTC, merged

2023-03-06 08:50 UTC, AaronFriel commented
@rquitales were you able to test this out on a repository? I'm noticing that with this change, `make install_plugins` *always* installs the Pulumi CLI:

```shell
$ make provider
make: command: Command not found
[ -x "" ] || curl -fsSL https://get.pulumi.com | sh
=== Upgrading Pulumi 3.50.2-dev.0 to v3.55.0 ===
...
```

When I revert this change, I get the expected behavior:

```shell
$ make install_plugins
[ -x /home/friel/.pulumi-dev/bin/pulumi ] || curl -fsSL https://get.pulumi.com | sh
# end of output, no installation
```

This is using GNU Make 4.2.1, Bash 5.0.17 on Ubuntu Linux 20.04.

2023-03-08 19:35 UTC, rquitales commented
@AaronFriel With the reverted change, I believe you would never install `pulumi` as it always returns true even if the `pulumi` binary is not found.

It seems like this change is always installing the CLI since `command` is not installed in that env. If `command` exists, then it won't install Pulumi CLI if it's already existing locally.

Looks like we're running into local env issues, where we can't assume that `command` comes preinstalled.

2023-03-08 19:42 UTC, AaronFriel commented
@rquitales `command` is not a program but a shell command. Does make behave correctly when shelling out to run shell commands which aren't binaries?

2023-03-08 19:51 UTC, rquitales commented
@AaronFriel seems to be working on both my Mac and a VM on GCP:

```
make install_plugins
[ -x "/opt/homebrew/bin/pulumi" ] || curl -fsSL https://get.pulumi.com | sh
# end of output, no installation
```

2023-03-08 23:11 UTC, AaronFriel commented
Interesting: https://stackoverflow.com/questions/12989869/calling-command-v-find-from-gnu-makefile

It looks like `make` can try to be clever.

2023-03-08 23:16 UTC, AaronFriel commented
Too clever: https://stackoverflow.com/questions/17547625/how-to-use-shell-builtin-function-from-a-makefile/17550243#17550243