Makefile and upstream.sh fixups
pulumi/ci-mgmt pull request #696
Opened 2023-10-18 20:41 UTC by danielrbradley

## [Simplify invoking scripts](https://github.com/pulumi/ci-mgmt/commit/2748725404c8830bdf8df4699c01acb5a310de19)
Add shebang to scripts/upstream.sh to specify its own expected shell and make it executable. Therefore...

1. Remove unneeded shell prefix in make (the shebang makes this obsolete).
2. Remove `@` prefix so we can see what we're running in case something goes wrong. Otherwise diagnosing issues requires reading the makefile and having to manually substitute in variables. This also provides a helpful record of commands in CI for troubleshooting.

## [Unnest pulumi-java-gen binary download command](https://github.com/pulumi/ci-mgmt/commit/c8a250d8388c1dbde140ee947856d22f3a639816) 

Using `$(shell ...)` inside a target is an anti-pattern as it can break the expected execution order, break --what-if, and hides commands being executed from logs.

## [Make patches less noisy](https://github.com/pulumi/ci-mgmt/commit/40caf9a5dd0d7fc15229c75cf21e6b6428b7a6d3) 

1. Remove the file path prefix of "a/" or "b/" in summaries as this isn't useful information.
2. Set source commit hash to all zeros otherwise this changes after every rebase.
3. Remove the git signature which is generally just the version number of git used to extract the patch.
4. Remove stats which just adds a big block of stats at the top of each diff which isn't useful to maintain.

## [Reset back to "HEAD mode" after finishing a rebase](https://github.com/pulumi/ci-mgmt/commit/2d9e7c0d8baba2306cbca406c511677120f1553f) 

Instead of leaving the user on a branch, move back to the referenced submodule commit ready to re-apply the patches.

## [Warn if finalizing mid-rebase](https://github.com/pulumi/ci-mgmt/commit/e8eb388fd4df311b011902ddbca51c2706d4a0dc) 

If we half way through a rebase, it's certainly an error to then attempt to extract the patches - as the commits not yet rebased will be missing from the patch set.

2023-10-18 20:50 UTC, danielrbradley commented
Looks like we don't maintain file permissions when copying the script ... just fixing up now.

2023-10-18 21:10 UTC, mjeffryes approved these changes
This really looks like a tool that should standalone and have some tests rather than being copied into every provider repo. However the proposed changes look reasonable.

2023-10-18 21:10 UTC, mjeffryes commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
This test looks to be redundant with the `assert_rebase_not_unfinished` you just added.

2023-10-18 22:28 UTC, iwahbe requested changes

2023-10-18 22:28 UTC, iwahbe commented on provider-ci/internal/pkg/generate.go
> +	}
Git does not maintain file permissions AFAIK. We shouldn't need this, and I don't believe it does anything for us.

2023-10-18 22:28 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
It isn't. `assert_rebase_in_progress` checks that `make upstream.rebase` has been called.

2023-10-18 22:28 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  git submodule update --force --init
This should just call the function to reset upstream.
```suggestion
  apply "$1"
```

This has the nice property of being DRY and asserting that the new patch set applies cleanly.

2023-10-18 22:28 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/Makefile
> +	scripts/upstream.sh "$@" apply
I would rather we called `scripts/upstream.sh` as a script, instead of as an executable. If you don't want to use `$(SHELL)`, we can specify bash directly.

```suggestion
	bash ./scripts/upstream.sh "$@" apply
```

2023-10-18 22:30 UTC, mjeffryes commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
No I mean the check in line 182 and following.

2023-10-18 22:32 UTC, mjeffryes commented on provider-ci/internal/pkg/templates/bridged-provider/Makefile
> +	scripts/upstream.sh "$@" apply
What's the motivation for running it in a subshell?

2023-10-18 22:32 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  git_status=$(cd upstream && git status --verbose)
Is it possible to get this with `git status --porcelain`? `--verbose` depends on your `git` implementation/version but `--porcelain` is part of `git`'s stable interface.

2023-10-18 22:33 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/Makefile
> +	scripts/upstream.sh "$@" apply
AFAIK it will be run in a sub shell regardless. I would prefer we invoke it via the executor to avoid worrying about executability.

2023-10-18 22:34 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
Oh... you're 100% right. Ignore me

2023-10-19 09:36 UTC, danielrbradley commented on provider-ci/internal/pkg/generate.go
> +	}
Yup - git maintains these. File archives don't maintain permissions.

2023-10-19 09:39 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/Makefile
> +	scripts/upstream.sh "$@" apply
Executability is what the shebang is for (`#!/usr/bin/env bash`)

[Wikipedia Reference](https://en.wikipedia.org/wiki/Shebang_%28Unix%29)

2023-10-19 09:41 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  git_status=$(cd upstream && git status --verbose)
No, porcelain doesn't include rebase status. It's not guarenteed to be there so it's possible we might not always prevent this case, but if it is there, we can be sure that the user is doing something wrong.

2023-10-19 09:44 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
`[ -d .git/modules/upstream/rebase-merge ]` doesn't work everywhere either - this completely failed to catch my own local rebase. Here's a good discussion of trying to catch a rebase ... essentially, there's no reliable way to do this https://stackoverflow.com/questions/3921409/how-to-know-if-there-is-a-git-rebase-in-progress

2023-10-19 15:41 UTC, mjeffryes commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
The SO answer you linked suggests that 
```
(test -d "$(git rev-parse --git-path rebase-merge)" || \
 test -d "$(git rev-parse --git-path rebase-apply)" )
```
is probably the most reliable option. 

At any rate, I'd just like to consolidate the old and new checks in a single place.

2023-10-19 20:52 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
>    if [ -d .git/modules/upstream/rebase-merge ]; then
Yup, agree, that seems to be a good in-between. Tested locally and this does actually catch the rebase unlike before.

2023-10-19 20:54 UTC, danielrbradley commented
@iwahbe I think all the converations should be resolved now with the follow-up changes now in. Were there any other changes outstanding that you see as blocking this getting merged?

2023-10-19 20:55 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  git_status=$(cd upstream && git status --verbose)
Remove this whole approache now.

2023-10-19 21:02 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  assert_rebased "$1"
Where is `assert_rebased` defined?

2023-10-19 21:02 UTC, iwahbe commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  rebase_apply_dir=$(cd upstream && git rev-parse --git-path rebase-apply)
A comment explaining what this does would be appreciated.

2023-10-23 09:47 UTC, danielrbradley commented on provider-ci/internal/pkg/templates/bridged-provider/scripts/upstream.sh
> +  assert_rebased "$1"
Ah - this was meant to go back to `assert_rebase_in_progress`. Fixed

2023-10-23 17:09 UTC, iwahbe approved these changes

2023-10-23 18:37 UTC, merged