chore: create upstream patch files with `--no-numbered`
pulumi/ci-mgmt pull request #883
Opened 2024-04-15 15:04 UTC by corymhall

Currently the patch files are generated with subjects that contain the patch number (i.e. `Subject: [PATCH 02/52] Add S3 legacy bucket to resources`). This makes diffs too verbose since everytime I add or remove a patch I have a diff on _every_ one of the patches.

The patches have the patch number in the name of the file already so the number in the subject is redundant.

2024-04-15 16:47 UTC, t0yv0 requested changes
I'm for this in principle but it needs to go to ci-mgmt as this edit will be wiped out:

```# WARNING: This file is autogenerated - changes will be overwritten if not made via https://github.com/pulumi/ci-mgmt
```

2024-04-15 16:55 UTC, corymhall commented
> I'm for this in principle but it needs to go to ci-mgmt as this edit will be wiped out:

This is in ci-mgmt 😀

2024-04-15 21:53 UTC, t0yv0 commented
Ah it trips me up that the templates have this "warning" copy.

2024-04-15 21:53 UTC, t0yv0 commented
Affects Ian's squad so adding as a reviewer. LGTM>

2024-04-15 21:53 UTC, t0yv0 approved these changes

2024-04-16 09:06 UTC, iwahbe approved these changes
LGTM

2024-04-16 11:59 UTC, merged